# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Portfolio"
  pageRef = "projects"
  weight = 10

[[main]]
  name = "Programming"
  weight = 10
  parent = "Portfolio"
  pageRef = "tags/Programmer"
  

[[main]]
  name = "Level Design"
   weight = 10
  parent = "Portfolio"
  pageRef = "tags/Level-Designer"

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 20
 
[[main]]
  name = "Developer Logs"
  parent = "Blog"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "About Me"
  pageRef = "About"
  weight = 30

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 #[[footer]]
   #name = "Categories"
 # pageRef = "categories"
 # weight = 20
